import fs from "fs/promises";
import path from "path";
import { getPageForCodegen } from "./client";

function normalizeRoute(route: string): string {
  return route.replace(/^\/+/, "").replace(/\/+$/, "");
}

/** Source for a generated index (list) page route handler. */
export function generateIndexRoute(pageId: string): string {
  return `// AUTO-GENERATED by the CMS — do not edit by hand.
// Regenerated whenever content is published or bindings change.
import { renderCmsIndex } from "@/lib/cms/render";

export const dynamic = "force-dynamic";

export async function GET() {
  const html = await renderCmsIndex(${JSON.stringify(pageId)});
  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
`;
}

/** Source for a generated detail page route handler (dynamic [slug]). */
export function generateDetailRoute(pageId: string): string {
  return `// AUTO-GENERATED by the CMS — do not edit by hand.
import { renderCmsDetail, getDetailSlugs } from "@/lib/cms/render";

export async function generateStaticParams() {
  const slugs = await getDetailSlugs(${JSON.stringify(pageId)});
  return slugs.map((slug) => ({ slug }));
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const html = await renderCmsDetail(${JSON.stringify(pageId)}, slug);
  if (!html) return new Response("Not found", { status: 404 });
  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
`;
}

/** Resolve where the generated file for a page should be written. */
export function targetFileFor(pageType: string, route: string): string {
  const norm = normalizeRoute(route);
  if (pageType === "detail") {
    const dir = norm.includes("[slug]") ? norm : `${norm}/[slug]`;
    return path.join("app", dir, "route.ts");
  }
  return path.join("app", norm, "route.ts");
}

/**
 * Regenerate the Next.js file(s) for a CMS page from the current bindings and
 * template. Writes a valid, runnable route handler to the app directory.
 * Returns the relative path written.
 */
export async function regenerateCMSPage(pageId: string): Promise<string> {
  const page = await getPageForCodegen(pageId);

  const relPath = targetFileFor(page.pageType, page.route);
  const absPath = path.join(process.cwd(), relPath);
  await fs.mkdir(path.dirname(absPath), { recursive: true });

  const source =
    page.pageType === "detail"
      ? generateDetailRoute(pageId)
      : generateIndexRoute(pageId);

  await fs.writeFile(absPath, source, "utf8");
  return relPath;
}

/** Regenerate all CMS pages (used after a bulk change or on deploy). */
export async function regenerateAllPages(pageIds: string[]): Promise<string[]> {
  const written: string[] = [];
  for (const id of pageIds) {
    written.push(await regenerateCMSPage(id));
  }
  return written;
}
